blog_app/urls.py
from django.urls import path
from . import views


app_name = 'blog_app'

urlpatterns = [
    path('', views.home, name='homepage'),
    path('search/', views.post_search, name='post_search'),
    path('<slug:post>/', views.post_detail, name='post-detail'),
    path('category/<category>/', views.CatListView.as_view(), name='category'),    
]

blog_pr/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls', namespace='blog_app')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/models.py
from time import timezone
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
# Create your models here.

def user_directory_path(instance,filename):
    return 'posts/{0}{1}'.format(instance.id,filename)

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name



class Post(models.Model):

    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status='published')

    options = {
        ('draft','Draft'),
        ('published','Published'),
    }
    title = models.CharField(max_length=250)
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, default=1)
    snippet = models.TextField()
    slug = models.SlugField(max_length=250, unique_for_date='pub_date')
    image = models.ImageField(upload_to=user_directory_path, default="posts/default.jpg")
    pub_date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE,related_name='blog_posts')
    content = models.TextField()
    status = models.CharField(max_length=10,choices=options,default='draft')

    objects = models.Manager()
    newmanager = NewManager()

    def get_absolute_url(self):
        return reverse('blog_app:post-detail',args=[self.slug])

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.title

class Comment(MPTTModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='comments')
    parent = TreeForeignKey('self',on_delete=models.CASCADE,
    null=True,blank=True,related_name='children')

    name = models.CharField(max_length=50)
    email = models.EmailField()
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['publish']

    def __str__(self):
        return f"Comment by {self.name}"

blog_app/forms.py
from django import forms
from .models import Category, Comment
from mptt.forms import TreeNodeChoiceField


class NewCommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)

        self.fields['parent'].widget.attrs.update(
            {'class':'d-none'}
        )
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comment
        fields = ('name','parent', 'email', 'content')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'col-sm-12'}),
            'email': forms.TextInput(attrs={'class': 'col-sm-12'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }
    def save(self, *args, **kwargs):
        Comment.objects.rebuild()
        return super(NewCommentForm,self).save(*args,**kwargs)

class PostSearchForm(forms.Form):
    q = forms.CharField()
    c = forms.ModelChoiceField(
        queryset=Category.objects.all().order_by('name'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        self.fields['c'].required = False

blog_app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, get_list_or_404
from django.views.generic import ListView
from . forms import NewCommentForm,PostSearchForm
from .models import Post,Comment,Category
from django.db.models import Q
# Create your views here.



def home(request):
    posts = Post.newmanager.all()
    context = {
        'posts':posts
    }
    return render(request, 'blog_app/index.html', context)

def post_detail(request, post):

    post = get_object_or_404(Post, slug=post, status='published')

    comments = post.comments.filter(status=True)

    user_comment = None

    if request.method == 'POST':
        comment_form = NewCommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.save()
            return HttpResponseRedirect('/' + post.slug)
    else:
        comment_form = NewCommentForm()
    return render(
        request, 
        'blog_app/post_detail.html', 
        {
        'post': post, 'comments':  user_comment, 
        'comments': comments, 
        'comment_form': comment_form
        }
    )


class CatListView(ListView):
    template_name = 'blog_app/category.html'
    context_object_name = 'catlist'

    def get_queryset(self):
        content = {
            'cat': self.kwargs['category'],
            'posts': Post.objects.filter(category__name=self.kwargs
            ['category']).filter(status='published')
        }
        return content

def category_list(request):
    category_list = Category.objects.all()
    context = {
        "category_list": category_list,
    }
    return context
    # to make available globaly go to settings.py and update TEMPLATES

def post_search(request):
    form = PostSearchForm()
    q = ''
    c = ''
    results = []
    query = Q()
    if 'q' in request.GET:
        form = PostSearchForm(request.GET)
        if form.is_valid():
            q = form.cleaned_data['q']
            c = form.cleaned_data['c']

            if c is not None:
                query &= Q(category=c)
            if q is not None:
                query &= Q(title__contains=q)

            results = Post.objects.filter(query)
            
    return render(request, 'blog_app/search.html',
     {'form':form,
     'q':q,
     'results':results
     })

blog_app/templates/blog_app/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Categories
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% for category in category_list %}
                  <li><a class="dropdown-item" href="/category/{{ category.name}}">
                    {{ category.name|title }}
                  </a>
                  {% endfor %}
                </li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      <div class="mt-3">
        {% block content %}{% endblock %}
      </div>
      
    </div>
    
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>

blog_app/templates/blog_app/category.html
{% extends "blog_app/base.html" %}

{% block title %}
Catlist
{% endblock %}

{% block content %}

   <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
    <div class="col-12 pb-5"><h1> List of {{catlist.cat}} posts</h1></div>
    {% for post in catlist.posts %}
        <div class="col-md-4">
        <a class="text-dark" href="{{post.get_absolute_url}}">
          <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
            <div class="card-body">
              <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
              <p class="card-text">{{post.snippet }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
          </a>
        </div>
    {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}

blog_app/templates/blog_app/index.html
{% extends 'blog_app/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
{% for post in posts %}
<div class="card mb-3" style="max-width: 900px;">
    <div class="row g-0">
      <div class="col-md-2">
        <img src="{{ post.image.url }}" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-10">
        <div class="card-body">
          <h5 class="card-title">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>

          </h5>
          <p class="card-text">{{ post.snippet }}</p>
          <p class="card-text">
              <small class="text-muted">
                  Published on - {{ post.pub_date }} Createdby - {{ post.author.first_name }}
                  {% if post.category %}
                  Category - {{ post.category|title }}
                  {% endif %}
              </small></p>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
{% endblock %}

blog_app/templates/blog_app/post_detail.html
{% extends "blog_app/base.html" %}

{% block title %}
Detail Page
{% endblock %}

{% block content %}

<style>
  @media screen and (min-width: 600px) {
    .children form {
      margin-left: -48px;
      /* will touch very left side */
    }

    .children .children form {
      margin-left: -96px;
      /* will touch very left side */
    }
  }
</style>

<div class="container">
  <div class="row justify-content-md-center pt-5">

    <div class="col-md-7">
      <h1>{{ post.title }}</h1>
    </div>
    <div class="col-md-9"><img class="card-img-top" src="{{ post.image.url }}" alt="{{ post.title }}"></div>
    <div class="col-md-7">
      <p>{{ post.content|safe }}</p>
    </div>
    <div class="col-md-7">

      {% with allcomments.count as total_comments %}
      <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
      </h2>
      {% endwith %}

      {% load mptt_tags %}

      <div>
        {% recursetree comments %}
        <div id="{{ node.id }}" class="my-2 p-2" style="border: 1px solid grey;">
          <div class="d-flex justify-content-between">
            By {{ node.name }}
          <div></div>{{ node.publish }}</div>
          <div>{{ node.content }}</div>
          <hr />
          {% if node.level < 3 %}
          <button class="button" onclick="myFunction({{ node.id }})">Reply</button>
          {% endif %}
        </div>
        {% if not node.is_leaf_node %}
        <div class="children pl-2 pl-md-5" style="padding-left: 10px;">
          {{ children }}
        </div>
        {% endif %}
        {% endrecursetree %}
      </div>

      <!-- <div class="py-4">
        <nav aria-label="Page navigation example">
          {% if comments.has_other_pages %}
          <ul class="pagination">
            {% if comments.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
            {% for num in comments.paginator.page_range %}
            {% if comments.number == l %}
            <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if comments.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </div> -->

      <div id="myDIV" style="display:block;">
        <form id="myForm" method="post">
          <h2>Create new comment</h2>
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
        </form>
      </div>

    </div>
  </div>
</div>
<script>
  function formExit() {
    document.getElementById("newForm").remove();
  }

  function myFunction(id) {
    if (document.contains(document.getElementById("newForm"))) {
      document.getElementById("newForm").remove();
    }

    var d1 = document.getElementById(id);
    d1.insertAdjacentHTML('afterend',
      '<form id="newForm" class="form-insert py-2" method="post"> \
                <div class="d-flex justify-content-between"><h2>Reply:</h2><div><button type="button" class="btn btn-outline-secondary" onclick="formExit()"">Close</button></div></div> \
                <label for="id_name">Name:</label> \
                <input type="text" name="name" class="col-sm-12" maxlength="50" required="" id="id_name">\
                <select name="parent" class="d-none" id="id_parentt"> \
                <option value="' + id + '" selected="' + id + '"></option> \
                </select> \
                <label for="id_email">Email:</label> \
                <input type="text" name="email" class="col-sm-12" maxlength="254" required="" id="id_email"> \
                <label for="id_content">Content:</label> \
                <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content"></textarea> \
                {% csrf_token %} \
                <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button> \
              </form>');

    //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
  }

  $('#myForm').trigger("reset");
</script>

{% endblock %}

blog_app/templates/blog_app/search.html
{% extends "blog_app/base.html" %}

{% block title %}
Search Page
{% endblock %}

{% block content %}

{% if q %}
<h1>Posts containing "{{ q }}"</h1>
<p>
    {% with results.count as total_results %}
    Found {{ total_results }} result {{ total_results|pluralize }}
    {% endwith %}
</p>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for post in results %}
            <div class="col-md-4">
                <a class="text-dark" href="{{post.get_absolute_url}}">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                        <div class="card-body">
                            <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                            <p class="card-text">{{post.snippet|truncatechars:50}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
{% empty %}
<p>There are no results for your query.</p>
{% endfor %}
<p><a href="{% url 'blog_app:post_search' %}" class="btn btn-primary mt-5" role="button">
    New Search
    </a>
</p>
{% else %}

<form method="GET">
    {{ form.as_p }}
    <input class="btn btn-primary my-1" type="submit" value="Search">
</form>

{% endif %}

{% endblock %}